CREATE TABLE CUSTOMER(
    CustomerID      INT          PRIMARY KEY AUTO_INCREMENT,
    CustomerName    VARCHAR(255) NOT NULL,
    CustomerAddress VARCHAR(255) NOT NULL,
    CustomerAge     INT          NOT NULL
);

CREATE TABLE FAVORITE(
    FavoriteID INT PRIMARY KEY AUTO_INCREMENT,
    CustomerID INT REFERENCES CUSTOMER(CustomerID) NOT NULL ON DELETE RESTRICT,
    WineID     INT REFERENCES Wine(WineID)         NOT NULL ON DELETE RESTRICT,
    DateAdded  INT NOT NULL
);
