CREATE TABLE CUSTOMER(
    CustomerID      INT          PRIMARY KEY AUTO_INCREMENT,
    CustomerName    VARCHAR(255) NOT NULL,
    CustomerAddress VARCHAR(255) NOT NULL,
    CustomerAge     INT          NOT NULL
);

CREATE TABLE FAVORITE(
    FavoriteID INT PRIMARY KEY AUTO_INCREMENT,
    CustomerID INT REFERENCES CUSTOMER(CustomerID) NOT NULL ON DELETE RESTRICT,
    WineID     INT REFERENCES Wine(WineID)         NOT NULL ON DELETE RESTRICT,
    DateAdded  INT NOT NULL
);

CREATE TABLE WINE(
    WineID   INT          PRIMARY KEY AUTO_INCREMENT,
    WineryID INT          REFERENCES WINERY(WineryID) NOT NULL ON DELETE RESTRICT,
    WineName VARCHAR(255) NOT NULL,
    WineYear INT          NOT NULL,
    WineCost DECIMAL(5,2) NOT NULL,
    WineABV  DECIMAL(5,2) NOT NULL
);

CREATE TABLE WINE_BROWSED_BY(
    WineBrowsedByID INT PRIMARY KEY AUTO_INCREMENT,
    CustomerID      INT REFERENCES CUSTOMER(CustomerID) NOT NULL ON DELETE RESTRICT,
    WineID          INT REFERENCES Wine(WineID)         NOT NULL ON DELETE RESTRICT,
    LastVisited     INT NOT NULL
);

CREATE TABLE WINE_MADE_FROM(
    WineMadeFromID INT PRIMARY KEY AUTO_INCREMENT,
    WineID         INT REFERENCES WINE(WineID)   NOT NULL ON DELETE RESTRICT,
    GrapeID        INT REFERENCES GRAPE(GrapeID) NOT NULL ON DELETE RESTRICT
);

CREATE TABLE WINE_STORED_AT(
    WineStoredAtID INT PRIMARY KEY AUTO_INCREMENT,
    WineID         INT REFERENCES WINE(WineID)       NOT NULL ON DELETE RESTRICT,
    StorageID      INT REFERENCES STORAGE(StorageID) NOT NULL ON DELETE RESTRICT
);

CREATE TABLE WINE_HAS_QUALITY(
    WineHasQualityID INT PRIMARY KEY AUTO_INCREMENT,
    WineID           INT REFERENCES WINE(WineID)       NOT NULL ON DELETE RESTRICT,
    QualityID        INT REFERENCES QUALITY(QualityID) NOT NULL ON DELETE RESTRICT
);
