CREATE TABLE CUSTOMER(
    CustomerID      INT          PRIMARY KEY AUTO_INCREMENT,
    CustomerName    VARCHAR(255) NOT NULL,
    CustomerAddress VARCHAR(255) NOT NULL,
    CustomerAge     INT          NOT NULL
);

CREATE TABLE FAVORITE(
    FavoriteID INT PRIMARY KEY AUTO_INCREMENT,
    CustomerID INT REFERENCES CUSTOMER(CustomerID) NOT NULL ON DELETE RESTRICT,
    WineID     INT REFERENCES Wine(WineID)         NOT NULL ON DELETE RESTRICT,
    DateAdded  INT NOT NULL
);

CREATE TABLE WINE(
    WineID   INT          PRIMARY KEY AUTO_INCREMENT,
    WineryID INT          REFERENCES WINERY(WineryID) NOT NULL ON DELETE RESTRICT,
    WineName VARCHAR(255) NOT NULL,
    WineYear INT          NOT NULL,
    WineCost DECIMAL(5,2) NOT NULL,
    WineABV  DECIMAL(5,2) NOT NULL
);

CREATE TABLE WINE_BROWSED_BY(
    WineBrowsedByID INT PRIMARY KEY AUTO_INCREMENT,
    CustomerID      INT REFERENCES CUSTOMER(CustomerID) NOT NULL ON DELETE RESTRICT,
    WineID          INT REFERENCES Wine(WineID)         NOT NULL ON DELETE RESTRICT,
    LastVisited     INT NOT NULL
);

CREATE TABLE WINE_MADE_FROM(
    MadeID  INT PRIMARY KEY AUTO_INCREMENT,
    WineID  INT REFERENCES WINE(WineID)   NOT NULL ON DELETE RESTRICT,
    GrapeID INT REFERENCES GRAPE(GrapeID) NOT NULL ON DELETE RESTRICT
);
